<?php

namespace Ocean;

class FastLog {
	const HISTORY_OTHER = 0;
	const HISTORY_ADD_DEVICE = 1;
	const HISTORY_UPDATE_DEVICE = 2;
	const HISTORY_DELETE_DEVICE = 3;
	const HISTORY_INSTALL_SOFTWARE = 4;
	const HISTORY_UNINSTALL_SOFTWARE = 5;
	const HISTORY_DISCONNECT_DEVICE = 6;
	const HISTORY_CONNECT_DEVICE = 7;
	const HISTORY_LOCK_DEVICE = 8;
	const HISTORY_UNLOCK_DEVICE = 9;
	const HISTORY_LOG_SIMPLE_MESSAGE = 12;
	const HISTORY_DELETE_ITEM = 13;
	const HISTORY_RESTORE_ITEM = 14;
	const HISTORY_ADD_RELATION = 15;
	const HISTORY_DEL_RELATION = 16;
	const HISTORY_ADD_SUBITEM = 17;
	const HISTORY_UPDATE_SUBITEM = 18;
	const HISTORY_DELETE_SUBITEM = 19;
	const HISTORY_CREATE_ITEM = 20;
	const HISTORY_UPDATE_RELATION = 21;
	const HISTORY_LOCK_RELATION = 22;
	const HISTORY_LOCK_SUBITEM = 23;
	const HISTORY_UNLOCK_RELATION = 24;
	const HISTORY_UNLOCK_SUBITEM = 25;
	const HISTORY_LOCK_ITEM = 26;
	const HISTORY_UNLOCK_ITEM = 27;
	const HISTORY_PLUGIN_LOG_SIMPLE_DEVICE = 1230;
	const HISTORY_PLUGIN_ADD_DEVICE = 1231;
	const HISTORY_PLUGIN_UPDATE_DEVICE = 1232;
	const HISTORY_PLUGIN_DELETE_DEVICE = 1233;
	const HISTORY_PLUGIN_INSTALL_SOFTWARE = 1234;
	const HISTORY_PLUGIN_UNINSTALL_SOFTWARE = 1235;
	const HISTORY_PLUGIN_DISCONNECT_DEVICE = 1236;
	const HISTORY_PLUGIN_CONNECT_DEVICE = 1237;
	const HISTORY_PLUGIN_LOCK_DEVICE = 1238;
	const HISTORY_PLUGIN_UNLOCK_DEVICE = 1239;
	const HISTORY_PLUGIN = 1000;

	const HISTORY_OPTIONS = [ //
		'HISTORY_OTHER' => self::HISTORY_OTHER, //
		'HISTORY_ADD_DEVICE' => self::HISTORY_ADD_DEVICE, //
		'HISTORY_UPDATE_DEVICE' => self::HISTORY_UPDATE_DEVICE, //
		'HISTORY_DELETE_DEVICE' => self::HISTORY_DELETE_DEVICE, //
		'HISTORY_INSTALL_SOFTWARE' => self::HISTORY_INSTALL_SOFTWARE, //
		'HISTORY_UNINSTALL_SOFTWARE' => self::HISTORY_UNINSTALL_SOFTWARE, //
		'HISTORY_DISCONNECT_DEVICE' => self::HISTORY_DISCONNECT_DEVICE, //
		'HISTORY_CONNECT_DEVICE' => self::HISTORY_CONNECT_DEVICE, //
		'HISTORY_LOCK_DEVICE' => self::HISTORY_LOCK_DEVICE, //
		'HISTORY_UNLOCK_DEVICE' => self::HISTORY_UNLOCK_DEVICE, //
		'HISTORY_LOG_SIMPLE_MESSAGE' => self::HISTORY_LOG_SIMPLE_MESSAGE, //
		'HISTORY_DELETE_ITEM' => self::HISTORY_DELETE_ITEM, //
		'HISTORY_RESTORE_ITEM' => self::HISTORY_RESTORE_ITEM, //
		'HISTORY_ADD_RELATION' => self::HISTORY_ADD_RELATION, //
		'HISTORY_DEL_RELATION' => self::HISTORY_DEL_RELATION, //
		'HISTORY_ADD_SUBITEM' => self::HISTORY_ADD_SUBITEM, //
		'HISTORY_UPDATE_SUBITEM' => self::HISTORY_UPDATE_SUBITEM, //
		'HISTORY_DELETE_SUBITEM' => self::HISTORY_DELETE_SUBITEM, //
		'HISTORY_CREATE_ITEM' => self::HISTORY_CREATE_ITEM, //
		'HISTORY_UPDATE_RELATION' => self::HISTORY_UPDATE_RELATION, //
		'HISTORY_LOCK_RELATION' => self::HISTORY_LOCK_RELATION, //
		'HISTORY_LOCK_SUBITEM' => self::HISTORY_LOCK_SUBITEM, //
		'HISTORY_UNLOCK_RELATION' => self::HISTORY_UNLOCK_RELATION, //
		'HISTORY_UNLOCK_SUBITEM' => self::HISTORY_UNLOCK_SUBITEM, //
		'HISTORY_LOCK_ITEM' => self::HISTORY_LOCK_ITEM, //
		'HISTORY_UNLOCK_ITEM' => self::HISTORY_UNLOCK_ITEM, //
		'HISTORY_PLUGIN_LOG_SIMPLE_DEVICE' => self::HISTORY_PLUGIN_LOG_SIMPLE_DEVICE, //
		'HISTORY_PLUGIN_ADD_DEVICE' => self::HISTORY_PLUGIN_ADD_DEVICE, //
		'HISTORY_PLUGIN_UPDATE_DEVICE' => self::HISTORY_PLUGIN_UPDATE_DEVICE, //
		'HISTORY_PLUGIN_DELETE_DEVICE' => self::HISTORY_PLUGIN_DELETE_DEVICE, //
		'HISTORY_PLUGIN_INSTALL_SOFTWARE' => self::HISTORY_PLUGIN_INSTALL_SOFTWARE, //
		'HISTORY_PLUGIN_UNINSTALL_SOFTWARE' => self::HISTORY_PLUGIN_UNINSTALL_SOFTWARE, //
		'HISTORY_PLUGIN_DISCONNECT_DEVICE' => self::HISTORY_PLUGIN_DISCONNECT_DEVICE, //
		'HISTORY_PLUGIN_CONNECT_DEVICE' => self::HISTORY_PLUGIN_CONNECT_DEVICE, //
		'HISTORY_PLUGIN_LOCK_DEVICE' => self::HISTORY_PLUGIN_LOCK_DEVICE, //
		'HISTORY_PLUGIN_UNLOCK_DEVICE' => self::HISTORY_PLUGIN_UNLOCK_DEVICE, //
		'HISTORY_PLUGIN' => self::HISTORY_PLUGIN, //
	];
}
